# fly.toml app configuration file generated for webmedia on 2025-04-13T02:38:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webmedia'
primary_region = 'nrt'

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_PROVIDER = 'sqlite'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
