app = "webmedia"
primary_region = "nrt"  # 東京リージョン

[build]
  builder = "nixpacks"

[env]
  DATABASE_PROVIDER = "postgresql"
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "data"
  destination = "/data"
